version: '3'

services:

  nginx:
    image: nginx
    container_name: nginx
    ports:
        - 80:80
    volumes:
      - ./nginx:/etc/nginx/conf.d
    depends_on: 
        - web

  mysql:
    image: mysql
    container_name: mysql
    ports:
      - 3306:3306
    environment: 
      - MYSQL_ROOT_PASSWORD:mysql
      - MYSQL_DATABASE:practice-docker
      - MYSQL_USER:mysql
      - MYSQL_PASSWORD:123
    volumes:
      - mysql_data:/var/lib/mysql

  web:
    build:
      context: .
    image: practice-docker
    container_name: practice-docker
    ports:
      - 8080:8080
    depends_on:
      - mysql

volumes:
  mysql_data: